### ISSUE TITLE
Protect the main branch

### ISSUE THREAD

**Issue by SchoolGuy** [cathedraal/StudentDatabase#2]
To prevent accidental loss of work, I would recommend using GitHubs branch protection rules to enforce the following things:

- The `main` branch cannot be deleted by anyone.
- No one can (force) push to the `main` branch.
- Everyone (including you) needs to open a Pull Request before being able to include code in the `main` branch.
- You as repository owner can merge Pull Requests that are opened against the `main` branch.

Documentation: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches

**Comment by cathedraal** [comment]
Implemented as of now.
